name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v4

    # JDK 21 설정
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # gradlew 권한 설정
    - name: Set gradlew permissions
      run: |
        chmod +x ./gradlew

    - name: Create application.yml
      shell: bash
      run: |
        mkdir -p src/main/resources
        cat << 'EOF' > src/main/resources/application.yml 
        ${{ secrets.APPLICATION_YML }}
        EOF

    # Gradle 캐시 추가 (빌드 속도 개선)
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    # gradle 빌드
    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Set SSH key permissions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    # ssh-agent 최신 버전
    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    # known_hosts
    - name: Add known_hosts
      run: |
        ssh-keyscan -H ed25519 43.202.65.157 >> ~/.ssh/known_hosts

    #- name: 기존프로세스 종료
    #  run: |
    #    kill -9 $(ps -ef | grep devops | grep -v grep | head -n 1 | awk '{print $2}') || true

    - name: Deploy to Server with rsync
      run: | 
         rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/libs/*.jar ubuntu@43.202.65.157:~/app

    - name: Run SSH commands
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@43.202.65.157 << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar ~/app/my-app-0.0.1-SNAPSHOT.jar > ~/app/log.txt 2>&1 &
        EOF
